### ISSUE TITLE
[Feature] Please turn off the audio filtering in Duke3D by default, please.

### ISSUE THREAD

**Issue by NastyFlytrap** [ZDoom/Raze#1020]
### Raze version

1.8.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

All the sounds become muffled and the shotgun for example just sounds like a deep shockwave than the actual sound of the gun

### Describe the solution you'd like

Make the audio sampling be nearest by default please

### Describe alternatives you've considered

Not using RAZE, which'd be a shame because its the most modern and refined build port

**Comment by coelckers** [comment]
No, this sounds like shit on any good stereo sound system. There the added noise sounds like noise and not like an enhancement. Aside from that this would require making a global setting game specific.

If you want actually better sound on Duke, there's a really good sound pack available here which I highly recommend: https://www.moddb.com/mods/duke-nukem-3d-high-quality-sound-effects

**Comment by NastyFlytrap** [comment]
> No, this sounds like shit on any good stereo sound system. There the added noise sounds like noise and not like an enhancement. Aside from that this would require making a global setting game specific.
> 
> If you want actually better sound on Duke, there's a really good sound pack available here which I highly recommend: https://www.moddb.com/mods/duke-nukem-3d-high-quality-sound-effects

Okay, but my issue isnt that i want better audio, i just want the original audio mixing, because the 'default' setting sets it to something other than nearest, which is my issue. 

Admittedly, in shadow warrior the difference is a lot less, and i didnt notice until i went back just to verify this what i was going to say and found out its actually there aswell.

Still, my issue is that the 'default' setting for OpenAL Resampler is not nearest, which changes how it sounds and you should leave it on nearest by default. In shadow warrior the difference is not relatively minor but in duke3d its stupidly big and makes everything sound like im listening to someone else play the game in the room next door with loud volume.

**Comment by coelckers** [comment]
The option to change the resampler is there so nothing's preventing you from getting closer to the original mixing (It won't be accurate anyway because AFAIK the original game mixed at 11 kHz where a lot less noise was created before passing it to the hardware.) But on this issue you will get wildly diverging opinions because on some speaker equipment adding the noise from a nearest sound mixer is acceptable while on others all you hear is the added layer of noise in the sound which sounds not good.

If you want to find out where the config is stored, type 'whereisini' in the console.

**Comment by sinisterseed** [comment]
Similar to what Graf said, this is indeed highly subjective as what sounds good to you may sound like garbage to others. I personally use the built-in speakers of my monitor, and believe it not they're not a steaming pile of crap, but even with such a setup, the original noise of Duke 3D is absolutely terrible for some of its ambient noises that quite literally scratch my ears. They sounded like crap even on my old speakers.

Duke simply sounds so bad, because this is just the quality of the sounds themselves, they are poor recordings. This is exactly why Shadow Warrior, Exhumed, and Blood all sound infinitely better by comparison, their sound effects are of higher quality so they don't give you the illusion of sounding muffled (well, okay, Exhumed also has some garbage sounds, but they just become quieter instead). World Tour has the sounds in lossless format if I recall, so the settings don't affect it, and you can see that the sound quality just isn't great there either.

You can mess with the settings to bring the original sound back, or something that sounds less muffled while retaining some of the charm of the original (I think Cubic down in the resampling settings was a good compromise between the two?), but I'm against changing the default considering the option is readily available for the user to tweak it as they please.
