### ISSUE TITLE
[BUG] SW: Switching maps with swtrek command resets your inventory

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#1026]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you switch maps, you are reset to only having a sword and some shurikens. In DOS, your inventory would be kept.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. start game, get some items
2. use swtrek command to load another level
3. inventory reset, you will only have ur sword and some shurikens

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
I'm not going to invest work on making legacy cheats accurate. If you need this, use the changemap and levelwarp CCMDs instead.

**Comment by sinisterseed** [comment]
> i have to use legacy unless i know the raze commands. is there a guide or list somewhere for how to use all the raze commands?

Ideally the wiki should have the information, only that it hasn't been updated in quite a while. It will need an update since plenty of things have changed now. I took some time to update it back when we dropped 0.7 as it marked a major milestone for us, but it needs another cleanup as various pieces of information are out of date (such as Polymost still being a thing, and my god it even points to 1.0.1 as the current release on some pages lol), and not being nearly comprehensive enough regading mod launch and console commands/launch parameters.
