### ISSUE TITLE
[Feature] Other Build engine games?

### ISSUE THREAD

**Issue by wesp5** [ZDoom/Raze#1105]
### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Are there any plans to add the other old Build Engine games to Raze? At least those that are supported by GDX?

**Comment by sinisterseed** [comment]
Short answer: There are no plans to support other Build games outside of what Raze is currently supporting.

Detailed answer:

Starting off with Ion Fury: It cannot be supported because it relies on specific EDuke32 extensions and features that cannot simply be ported back. When the project originally started, Raze used EDuke32 as its base, however, after running into too many difficulties with the codebase, we decided to drop it after version 0.6. The old_master still available on the repo contains the original base, including an operational, albeit buggy and incomplete implementation of the game.

We have attempted to port some of the other games, initially starting with Witchaven and actually using BuildGDX as a base directly, but we quickly realized that the amount of effort required to port, fix, and then improve those games is far too great considering their obscure status and also very low quality.

There is also Duke Nukem 64. Similarly, adding support for it is also no easy task, as RedNukem, which supports it, also comes with an ancient version of OpenGL as a mandatory prerequisite, which is entirely incompatible with our base. In order to support it, the whole game would have to be reworked, which is an unrealistic goal.

We're not opposed to the idea of others, if interested, to pursue these tasks themselves and merging them. But we have determined that effort is much better spent elsewhere, as the amount of effort required to support those games properly vastly exceeds the demand and interest in them (combined with their abysmal quality in some of those cases).
