### ISSUE TITLE
[Feature] Import old saves

### ISSUE THREAD

**Issue by eadmaster** [ZDoom/Raze#1107]
### Raze version

Raze 1.9.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

is it possible to import old saves from the original game?

e.g. i have this old autosave file for SW

[gamex.zip](https://github.com/user-attachments/files/16646049/gamex.zip)

### Describe alternatives you've considered

start the game from the beginning and lose any progress made

**Comment by sinisterseed** [comment]
Long story short, no, this can never become a thing.

This is not possible due to the fact that Raze uses an entirely different save format from the DOS versions. Matter of fact, VoidSW, SWP, Redux, or BuildGDX saves are also not compatible with Raze. And they themselves are not compatible with each other either.

Additionally, we even break compatibility with our own old versions, once changes too substantial are introduced, causing inevitable breakage and requiring a save version bump.

**Comment by eadmaster** [comment]
Chocolate Doom has savegame compatibility with Vanilla Doom ([source](https://www.chocolate-doom.org/wiki/index.php/Savegame_compatibility)).
Do you know any other port that may have this feature?

**Comment by sinisterseed** [comment]
That's not a valid comparison. Build is not idtech, nor is Shadow Warrior Doom.

Also, Chocolate Doom aims to be a vanilla perfect engine, with the sole difference being its ability to run Doom on modern systems. 

Raze is neither a demo compatible engine nor is it a straightforward port of the original DOS releases, so this is out of scope for the project. You could try using DOS saves into one of the aforementioned ports and remasters and see how far that goes, but I don't recall them to be able to load DOS save files either. I could be wrong, though.
