### ISSUE TITLE
[Question] [Duke 3D] Loading HRP from .zip

### ISSUE THREAD

**Issue by laxdragon** [ZDoom/Raze#258]
With eduke3d I can just plop the duke3d_hrp.zip into the autoload dir and it loads the HRP just fine. I've been unable to get Raze to accomplish the same thing.

config:
```
[GameSearch.Directories]
Path=.
Path=./games
Path=./games/blood
Path=./games/duke3d
Path=./games/redneck
Path=./games/sw

[FileSearch.Directories]
Path=$PROGDIR
Path=$GAMEDIR
```

In ./games/duke3d I have an autoload subdir, and my .zip for the HRP is there. I've also tried moving the .zip to right next to the .grp and that didn't work either.

**Comment by coelckers** [comment]
Raze does not have an "autoload" directory. With an engine supporting multiple games that have nothing in common but the rendering engine this would not work because such files would get picked up by all games.

Autoloading works through the INI file. 
Add a section:

[Duke.Autoload]
Path=path_to_hrp\duke3d_hrp.zip

**Comment by laxdragon** [comment]
Thanks. This wasn't documented or included in the default .ini.
