### ISSUE TITLE
[General/Feature Request] Allow actual resolution switching instead of simple scaling

### ISSUE THREAD

**Issue by DukeSkinny** [ZDoom/Raze#276]
I like to play on my VGA monitor, and I'm having trouble getting a true 640x480 (or 400p, 200p, 600p, etc.) image. This issue is naturally duplicated in GZDoom as well.

Current behavior seems to simply scale the displayed image based on the fixed desktop resolution, which is great for LCDs, but these games were made for CRTs initially and it'd be a shame if they were forgotten.

If this request is non-trivial to implement or simply awkward at the current stage I won't make any further noise, just dropping it here in case.

**Comment by sinisterseed** [comment]
I think it is very safe to say that this is never happening.

The way resolution and scaling currently works is the same as GZDoom, which took a different route a few years ago, and it's not going back to the old ways of doing things.

This would also not be a trivial change either, it's a fundamental change to how it works.

**Comment by coelckers** [comment]
Problem is that OpenGL cannot do resolution switching. You have to change the system's desktop size at run time which is a major issue with resource maintenance and global state management because it is all taken down by the OD. It was causing so many problems when it was still available in GZDoom that this alone prevented sanitizing the backend.

By now the backend has changed sufficiently that it cannot be brought back anymore.

**Comment by mjr4077au** [comment]
Easiest thing to do is if you want 640x480 on your CRT, set Windows to that resolution and launch it in full screen on that monitor, it works well and I've done it before.
