### ISSUE TITLE
[Question] [Duke 3D] Is it possible to convert older save files?

### ISSUE THREAD

**Issue by mortimerprime** [ZDoom/Raze#284]
I was playing Duke 3D in Raze 0.6, and downloaded the new v 0.9 yesterday (awesome work!)
When I went to load save games that I had copied over, it said something like "incompatible save games".
Is there a util or something to convert older saves? I assume when v 1.0 is released, I'll be faced with the same problem!
Thanks!
Alex

**Comment by sinisterseed** [comment]
No way.

There have been a great many deal of changes since version 0.6, especially with Duke 3D which has since seen a complete rebase from older sources, specifically JFDuke3D, EDuke 2.0, and GDX for native World Tour support. We no longer use EDuke32 as a base for it. This also means that the incomplete support for Ion Fury is gone, and it will not return as it requires proper support for all EDuke32 extensions.

Sometimes, save version bumps are inevitable when the game internals or the format itself sees a number of changes and revisions, which will lead to broken saves, but in this case, it goes beyond even that as the game is quite literally not the same anymore.

**Comment by coelckers** [comment]
It was also a deliberate choice not to add any savegame upgrade code befoew reaching version 1.0. Due to some things not being finished this would accumulated a lot of baggage. 
But yes, this case is different, as the entire format of the save files has changed.
