### ISSUE TITLE
[BUG] [SW] Brown Ripper's hitbox

### ISSUE THREAD

**Issue by NineKain** [ZDoom/Raze#305]
I used the rocket launcher on the Brown Ripper in level 6: Killing Fields like 3 times, didn't hit once whilst clearly hitting him right in the center, the two next rockets hit perfectly. Might be a hitbox problem.

**Comment by sinisterseed** [comment]
This may actually just be Build being Build as opposed to a game bug. We have not touched any monster hitbox or anything of sorts either.

Build's explosions are notoriously inconsistent, most noticeable in Blood due to its arsenal. Dynamite exploding near enemies on the ground does nothing sometimes, while other times with groups, either the whole group goes kaboom,or just the first enemy does. 

This extends to the player as well, sometimes a close explosion almost kills you, other times, let's say, just a flesh wound.

**Comment by NineKain** [comment]
No, it was the 3 first hits that didn't register haha, but maybie it's build being build.

**Comment by sinisterseed** [comment]
I tried this multiple times today to see what I get, and it was pretty much fine for me, only once in one attempt I had not heard any pain sounds when hitting. Tried the grenade launcher as well for comparison.

So, unless there turns out to be a bigger issue buried deep, I'm considering this just Build at its finest - consistently inconsistent blast damage.
