### ISSUE TITLE
[Question] What are the odds of getting TekWar support?

### ISSUE THREAD

**Issue by TheOldKingCole** [ZDoom/Raze#411]
I don't have high expectations for a positive answer I'm just want to troll people with tekwar in 4k

**Comment by Gaerzi** [comment]
I think you'll have a better chance with BuildGDX for that. The games currently supported are the only games planned at the moment; for Witchaven, Tekwar, Paintbrawl, Legend of the Seven Paladins, and whatever other oddities one might unearth, there's either no sources or a source release of dubious legality; combined with generally poor-to-horrible gameplay.

In fact I'm pretty sure that if NAM and WWII GI weren't glorified Duke TCs that don't really need much investment to make work, they wouldn't be supported either.

**Comment by coelckers** [comment]
The main problem with both is that there is no ready-to-use source.
The original DOS sources are in a state that's close to unusable - i.e. the code quality is considerably worse than Duke and SW - and the only alternative is GDX which is Java.

Actuallly, porting the game logic itself is not such an issue, but integrating it in the new framework is tricky due to the low quality or the differences to GDX.
So, they may come in the future, or they may not come. I won't make any promises either way.

**Comment by Dzierzan** [comment]
@Gaerzi 
Wait a sec, "there's either no sources or a source release of dubious legality" I am sorry, but reverse engineered sources of Blood, Powerslave and Redneck Rampage aren't really more legal than that.

@TheOldKingCole 
Just use BuildGDX if you wanna play those below average games badly.

**Comment by sinisterseed** [comment]
> So anyway, IMO it should be closed. It's not an issue.

But it is a request. And it may, or may not ever happen.

**Comment by TheOldKingCole** [comment]
I'm going to close it I was just curious.

**Comment by Gaerzi** [comment]
@Dzierzan: for good or for ill, reverse-engineered code is more readily accepted than leaked code. Cf. Strife or Doom 64, whose reverse engineering efforts even got, much latter, an official seal of approval thanks to Nigthdive's efforts.

**Comment by coelckers** [comment]
Acceptance or not - it only shows a considerable misunderstanding of the legal side of things.

In reality there are strict laws about reverse engineering - notably the prohibition of reverse engineering to develop competing products, so from a legal standpoint it's really a wash. 
Yes, the reverse engineers put in a lot of work, but the end result is no different from using source code illegally obtained.

But here's the big question: Is the source of those Capstone games "illegally obtained"? It hinges on a question we cannot answer, i.e. did the developer who released the source have the right to do so?

Even if the answer is "unlikely, but maybe" that's still more than the legality of the reverse engineering which in most jurisdictions is clearly forbidden.

**Comment by The-King-of-Toasters** [comment]
Regarding the licensing issue, I emailed SNEG - who are publishing a port of Witchaven to [Steam](https://store.steampowered.com/app/1655410/Witchaven/)/GOG. My message is as follows:

> I have some questions:
>
> - How did you acquire the distribution rights to Witchaven in the first place? Did you purchase all rights to the series? Who did you buy it from?
> - Do you have any connection with Ziggurat Interactive, who published other Capstone games like Corridor 7?
> - Capstone dev Les Bird released the source code for Witchaven I and II along with TekWar some time ago[1]. If you have the full rights to the game, are you willing to release the source code under a more permissive license (e.g. GPL2+ like Duke3D)? I realise that Siege of Avalon forced you to share improvements due to the existing LGPL license, but would it be nice for source port devs to hack on the code without resorting to reverse-engineering.
> - Is this version simply a wrapper around dosbox or does it use a custom build engine port a la Duke Megaton or Blood: Fresh Supply?
>
> [1] https://lesbird.github.io/capstone/index.html

Their response:

> Hi Stephen,
>
> Thanks for your e-mail and interest in Witchaven. Hope you understand that
we can't reveal all the details and answer all your questions in details.
Still, let us try.

> - Witchaven is licensed from Throwback Entertainment and distributed by our team.
> - We don't have any connection with Ziggurat guys.
> - We are not the rights holders of Witchaven IP and thus it is not a question to us.
> - Current version will be based on EGwhaven enhancements that we've licensed for this re-release and original versions of the game wrapped in DOSBox.
>
> Hope this answers your question.
>
> Best regards,
> SNEG Team

Interesting that they're using [EGwhaven](https://ettingrinder.youfailit.net/wh-egwhaven.html), as it's based on Les' source code (It's still DOS project though). Since it fixes a number of game bugs it might be better to base any Witchaven code on it. I'll try to contact Throwback to see if they can relicense the code.
