### ISSUE TITLE
[Feature] [Blood] Blood's interpolation in other games

### ISSUE THREAD

**Issue by NineKain** [ZDoom/Raze#584]
### Raze version

Raze 1.2.1

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Can we get Blood's weapon interpolation in the other shadow warrior games? Is it possible or is it harcoded to be only for Blood?

**Comment by mjr4077au** [comment]
Each game has its own weapon drawer. Blood's uses a format called QAV and the interpolation system in use is written expressly for that system. There's no aim or desire to port QAV to the other games since it has its own limitations, works on binary files and only has DOS editing tools. 

When we set up interpolation, all we wanted to achieve was smoothing of the weapon switching. With how QAV works, to get that going meant doing the entire system you see in-game, so it wasn't much effort to extend it throughout all the animations. The other games are a lot more simple in their design which allowed smooth bobbing and weapon switching without complicated systems, however its their simplicity which now does not permit such an advanced interpolation system.

**Comment by NineKain** [comment]
Than you for the detailed explanation
