### ISSUE TITLE
[Feature] Command line auto-load parameter

### ISSUE THREAD

**Issue by DralafiXIII** [ZDoom/Raze#655]
### Raze version

1.4.1

### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

No auto-launch capabilities.

### Describe the solution you'd like

Add a command line parameter that allows you to auto-load supported games. This would allow users to create separate shortcuts for each game rather than bringing up the launcher (if support for this already exists, I didn't see any documentation for it).

**Comment by arrowgent** [comment]
raze -iwad blood.rff
raze -iwad duke3d.grp
raze -iwad sw.grp

the only one that doesnt work with this is powerslave-exhumed
raze -iwad STUFF.DAT
as it will still open the launcher and ask for STUFF.DAT again

**Comment by DralafiXIII** [comment]
Thanks for the update! Any plans to fix the powerslave-exhumed command line?

Can anyone contribute to the project? Can I fix it?

**Comment by DralafiXIII** [comment]
Also it doesn't work with blood.rff. Haven't tried with sw.grp yet, but duke3d.grp works fine.

**Comment by not43s** [comment]
It is difficult to do this because Raze has no idea which files to load in which order. This puts a lot of burden on the launcher (and devs) to try and "figure out" the user intentions and sometimes its not pretty e.g. `-cryptic` flag

I recently added Raze to Batocera and worked around this by doing the following:
- Put roms somewhere that is not picked up by GameSearch.Directories (this keeps launcher from starting)
- Use `-gamegrp` arg for base game e.g. `-gamegrp PATH`
- For each expansion or mod, add `-file` arg e.g. `-file PATH`
- Where PATH is an absolute path to a GRP, ZIP, Launcher file, etc.

This works for examples like launching Blood: Cryptic Passage e.g. `raze.exe -gamegrp PATH/blood/BLOOD.RFF -file cryptic.zip`

**Comment by coelckers** [comment]
> raze -iwad STUFF.DAT as it will still open the launcher and ask for STUFF.DAT again

Works fine for me. Apparently it did not find the file.

> It is difficult to do this because Raze has no idea which files to load in which order.

Of course not. It's a game engine and not a clairvoyant. It's up to the user to provide proper order.

> e.g. -cryptic flag

That's why the recommended way to handle Cryptic Passage and Route 66 add-ons is to zip them up and load them regularly.

**Comment by coelckers** [comment]
Anyway, all the real issues pointed out here come from the engine not finding the named files. They either need to be in the current directory or in one that's in GameSearch.directories.
