### ISSUE TITLE
[BUG] [Duke] Stretched out sprites with Raze3D renderer

### ISSUE THREAD

**Issue by ericcarl** [ZDoom/Raze#673]
### Raze version

1.4.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### If Other OS, please describe

10.14.6

### Relevant hardware info

2015 MacBook Pro Intel, AMD Radeon R9 M370X

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Many, but not all, sprites in Duke Nukem 3D appear extremely stretched out and off position when using the Raze3D renderer. The issue doesn't seem to appear when using the Polymost renderer.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Fire up E1L1
2. Head to the bathroom and check out the urinals for the most pronounced effect

![Screen Shot 2022-04-08 at 11 28 51](https://user-images.githubusercontent.com/86512/162411193-a1772cf8-2226-43b6-9c17-18b9738810b2.png)
![Screen Shot 2022-04-08 at 11 34 41](https://user-images.githubusercontent.com/86512/162411305-c16c7b26-d1fa-4bf8-a986-597b995c6784.png)

### Provide a Log

https://www.dropbox.com/s/xmi1d8gzdgfcnec/raze.log?dl=0

**Comment by coelckers** [comment]
I cannot reproduce this, neither on Windows nor macOS. 
Does this also happen when using the Vulkan or GLES backend?

**Comment by jeanravin** [comment]
Same problem here with Blood using macos 11.6.6 and the same Raze version. The grate in the cemetery (where you pickup the flare gun) is distorted.

I finished Blood and SW using, I think, 1.2 and this bug wasn't there. (I was using macos 10.15 at the time)

[raze.log](https://github.com/coelckers/Raze/files/8884057/raze.log)

**Comment by jeanravin** [comment]
Further testing : no bug in 1.3.1, bug in 1.4.0

**Comment by mjr4077au** [comment]
@ericcarl is there any chance you can get off 10.14 and onto a newer release? 10.14 went EOL back in October 2021 and getting you onto supported software would be the first process of elimination since none of the development team is experiencing this.

It's not to say there isn't potentially something wrong in our code base, but a newer macOS release with an updated kernel and driver could resolve your issues here.

**Comment by jeanravin** [comment]
Same bug with macos 11… by the way…

**Comment by mjr4077au** [comment]
I think in this case it's just going to have to wait until some else experiences the issues but is able to help with a bit of debugging.

If you're in a position where you feel comfortable compiling Raze yourself and can help with some bisection to isolate the offending commit, that would be most helpful.

**Comment by jeanravin** [comment]
> If you're in a position where you feel comfortable compiling Raze yourself and can help with some bisection to isolate the offending commit, that would be most helpful.

Well… I'm sure not an expert. I already built a few apps, though. I followed this [guide](https://zdoom.org/wiki/Compile_GZDoom_on_Mac_OS_X_11.2.2) but I have some difficulties building the zmusic library. Maybe because of this : 

> VGM/GYM: MAME YM2612 emulator will be used
 ** ZLib library located, compressed file formats will be supported

**Comment by coelckers** [comment]
Those are just harmless informative messages.

**Comment by jeanravin** [comment]
OK

I finally managed to get my zmusic libraries and got my raze xcode project.

![Capture d’écran 2022-07-25 à 19 30 47](https://user-images.githubusercontent.com/1174299/180838952-0d26df64-b371-478a-a77c-5c9cc4d519a9.png)


I ran the raze "scheme" but I apparently still have trouble with zmusic : 

> dyld: Library not loaded: @rpath/libzmusic.1.dylib
  Referenced from: /Users/xxx/Raze/build/Debug/raze.app/Contents/MacOS/raze
  Reason: image not found
(lldb) 

Maybe a name/version issue ? Mine is "libzmusic.1.1.10.dylib"…

------

I just renamed it… (yeah I should have rebuilt the correct version but…)

So it finally worked v 1.6-pr17-xxxxxx AND the bug is not here (in Blood) ! I'll check the locations in duke nukem 3d…

**Comment by mjr4077au** [comment]
Thank you for doing this! I feel bad but I neglected to mention that 1.5 came out two days ago and might have saved you the compile effort...

How did the other tests go?

**Comment by mjr4077au** [comment]
It's always good to learn, and you're probably a step ahead of even myself as I haven't ever built Raze on a macOS environment before.

Thank you for confirming it's been resolved as well. I'll be curious as to what actually fixed this as it's something that never came up for us in development, but please let us know if it happens again.

Happy gaming!

**Comment by coelckers** [comment]
Since nothing had changed about the source code, I'd suspect a compiler bug in the version that was used for the 1.4.1 release.
