### ISSUE TITLE
[Feature] Make build editor work on Apple Silicon

### ISSUE THREAD

**Issue by mtoensing** [ZDoom/Raze#714]
### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

I can't edit maps on macOS with an M1 machine.

### Describe the solution you'd like

a build editor executable.

**Comment by madame-rachelle** [comment]
This unfortunately is beyond the scope of Raze. Raze is a platform for playing the games, it does not include an editor and that is expected to be done with third party tools.

**Comment by mtoensing** [comment]
Is there another way to use the build code for the editor on macOS m1?

**Comment by madame-rachelle** [comment]
It's possible to compile EDuke32 for Mac, so it may also be possible to compile Mapster, but I have yet to try it and I don't know if it will work.

If there's an Intel-only version on Mac though that will still work because OS Monterey still has Rosetta and I am sure future Mac OS releases will continue to do so for the foreseeable future, at least for the next half decade or so.

**Comment by mtoensing** [comment]
I could not find Mapster for intel Mac either
