### ISSUE TITLE
[BUG] [Exhumed] Several errors

### ISSUE THREAD

**Issue by orderorder** [ZDoom/Raze#721]
### Raze version

1.6pre-584-gab3e7df1b

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Manjaro Linux 22.0.0

### Relevant hardware info

AMD A10-7850K Radeon R7 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Exhumed: excessively fast weapon swing

Exhumed: wont load the savegame with "boolean type expected for camera / 1 errors parsing JSON" error

Note: 
i have upload a gif with the level 16 switch behaviour in NBlood proyect (Closed issue https://github.com/ZDoom/Raze/issues/674) https://user-images.githubusercontent.com/7293829/195167339-38cba6e2-ad9e-4f82-8b4e-9474ece03122.gif

### Steps to reproduce the behaviour.

Play game.

Save game and then load game.

**Comment by coelckers** [comment]
Please note that I am currently adding commits from a wotk branch to master.
The weapon problem is already fixed in that branch but it may take a few days to review all the code in-between before it can be integrated.

For savegames, the current master branch can NOT load older savegames as we go through a period where constant changes are being made to some data fields. Things should stabilize once this refactoring job is complete, but that can take a few weeks as it is a lot of work to get made ready.

**Comment by coelckers** [comment]
The weapon is working again, can't do anything about the rest.
