### ISSUE TITLE
[BUG] GLES2 rendering broken

### ISSUE THREAD

**Issue by dhwz** [ZDoom/Raze#722]
### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Other

### Please describe your specific OS version

Linux ARM

### Relevant hardware info

RK3399, RK3326 with MALI GPU (GLES2)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

somewhere between commit 3242b8fd81927b650e1a35554e3b931dec46bc1a and bd6b0eaac563cab26d041a4095126f2e0186aa09 the GLES2 renderer got badly broken. While walking around in Duke Nukem 3D the textures are just disappearing.

![rn_image_picker_lib_temp_1efe6c1d-ff41-467d-9b41-1212949d4789](https://user-images.githubusercontent.com/3697946/196033737-a4127ff1-afdd-456c-a9a8-fa9e4d282015.jpg)
![rn_image_picker_lib_temp_57f378b8-6803-4347-aeed-f8eed2166075](https://user-images.githubusercontent.com/3697946/196033748-1d849d82-2fa1-4435-a1fc-71365ea6045d.jpg)
![rn_image_picker_lib_temp_e439d70d-0670-4c1e-b1ce-4a596f41dac5](https://user-images.githubusercontent.com/3697946/196033753-b4a96213-2962-499a-a400-bc1938dcf20b.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
I am unable to reproduce the problem on my desktop system with any of the 3 backends, so I'm going to need help here narrowing it down. Can you try compiling a few commits between these two points and check where things start to break down?

**Comment by dhwz** [comment]
Yes of course, I'll try to narrow it down to a specific commit.

**Comment by dhwz** [comment]
@coelckers it's working properly up to this commit 3242b8fd81927b650e1a35554e3b931dec46bc1a, but I'm suspecting on of these commits between where biangle was changed to DAngle is breaking it, probably not only on Duke engine, thats just the one I've tested it on.
After that commit I can't compile till bd6b0eaac563cab26d041a4095126f2e0186aa09 fixed the compile issues on Linux.

**Comment by Halcyon522** [comment]
If it helps, I can confirm the same issue on my raspberry pi.

**Comment by coelckers** [comment]
1.4.1 is way too old, We need checks between the two commits linked in the post above by someone who can temporarily fix the code to compile again.

**Comment by dhwz** [comment]
@coelckers that is unfortunately beyond my capabilities
Hope someone else who can reproduce the issue can help

**Comment by Chatplosion** [comment]
This seems to be an error related to ARM64 based systems only. I have it on my Hardkernel N2+ too. The ARM fraction is the most complicated with its unique design. Maybe developers should buy ARM64s too.
My version is 1.6pree-1999-g5ebf2fef89.

**Comment by mjr4077au** [comment]
> This seems to be an error related to ARM64 based systems only. I have it on my Hardkernel N2+ too. The ARM fraction is the most complicated with its unique design. Maybe developers should buy ARM64s too. My version is 1.6pree-1999-g5ebf2fef89.

We probably should buy a PPC and Loongson setup as well, yeah? Surely you can't expect us to own hardware of all architectures to debug such edge cases?

I mean, I'll take one for free if you're offering? I'm in Sydney, Australia 🙂

**Comment by Halcyon522** [comment]
I'd happily send you an RPI 4 if they weren't so damned hard to get right now.

**Comment by mjr4077au** [comment]
What someone needs to do is create a branch at 3242b8fd81927b650e1a35554e3b931dec46bc1a where the issues hadn't started, start cherry picking each commit above it one-by-one, fixing the constexpr issues so that it builds and let us know precisely where it breaks.

The issue is probably somwwhere in the code that changes the clipangle or bunch drawer stuff, but it all works fine on Windows and Linux so we can't test much further than that.

**Comment by emileb** [comment]
Just seen this. Yes this most likely something to do with ARM, I remember ZDoom has something similar to do with converting angles and clipping, something about technically undefined behaviour.
When I update Raze Touch I think I will face the same issue and can take a look then.

**Comment by emileb** [comment]
Found it, maybe related? https://www.doomworld.com/forum/topic/72804-zdbsp-output-incorrect-on-arm-processors/

**Comment by coelckers** [comment]
I think that old issue has long been addressed.

**Comment by Chatplosion** [comment]
With the newest Version from master branch it is impossible to start whatever game you want. It freezes with a fullscreen window. Nothing is working.
Clearly a GL/GLES problem.

**Comment by mjr4077au** [comment]
Our lovely @madame-rachelle has addressed this in 6b8bdcc449210092fed874f10fe8af928ab89fc8. Please let us know if there's any further issues.

@Chatplosion, since your issue is reported against GZDoom as well, a fix there will fix it here as well. If you want one open in this project, feel free to open another one as your problem isn't directly related to this.

**Comment by coelckers** [comment]
My problem with this code is that no longer can perform const conversions. I think a better fix would be to first cast to 64 bit ints before truncating to 32 bit. Such code can be resolved at compile time and still be robust enough againt too large values

**Comment by madame-rachelle** [comment]
Can you be more specific? This was a solution that myself and mjr collaborated in order to provide a band-aid fix for the issue, as I understand it the long-term goal is to eliminate binangles completely and use normal radians and vectors like GZDoom does.

Were you looking for something like ... `return angle_t(int64_t(rad * (0x80000000u / M_PI)));` ?
