### ISSUE TITLE
[BUG] Underwater effect changes

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#761]
### Raze version

master 133cb3a02e

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As the player swims around, the screen colour effect changes according to the "ceiling" (water surface) texture. For example, if you dive in water, but swim under slime, the screen turns from blue to green. This should not happen, since it didn't happen in the original DOS version of the game.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10031121/save0002.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Dive in the water
3. Swim under the slime

OR

1. Load the saved game
2. Dive in the slime
3. Swim under the water

**Comment by coelckers** [comment]
This does not happen in the original game because it is very careless with the maintenance of this effect.
Restoring it would necessitate bringing back some buggy code. 
Besides, I like this better anyway. :)

**Comment by sinisterseed** [comment]
Same here.

I'm going as far as to say the original behavior was either an oversight, or a limitation, just like the HUD color changing when submerging into water. It's much more sensible to have it work this way.

**Comment by coelckers** [comment]
I can assure you that it was just the result of some very bad implementation. The underwater palette code in the original was disastrous. Instead of just picking the info from the current sector it went through several layers of nonsense to copy the value around which then, deep in the renderer was evaluated in a way that caused secondary problems
I ended up throwing it all out and go the easy and direct route to the info in the current sector. That of course means that if two sectors do not share the same palette, it will update now.

**Comment by NY00123** [comment]
Found out this is a dup of #186.

I originally planned to comment about this in #186 itself, but since I already started to comment here:

As mentioned in #186, there are still certain instances (e.g., the slime pool in E1L6) in which the original behaviors make more sense. Over there, the slime palette was intended to be used for the whole time, only that it'll be done just under actual slime tiles now.

Doesn't mean behaviors have to be 100% the same as the original; See, e.g., what happens when you repeatedly toggle the night vision goggles in an original DOS version while not below the slime tiles.

Given the current process of scriptifying, I thought this would be a good chance to remind of this before it might be too late.

**Comment by coelckers** [comment]
Scripting won't help here. This would require bringing back some very broken logic, making the tint solely dependent on the sector you dive in. So if you surface in the 'wrong' part and then dive again, the color will change.

**Comment by NY00123** [comment]
My main concern with the new comment was the possibility that the scriptifying process itself could make a fix much more difficult, if not impossible, in the future; At least not without a mod.

Either way, I rechecked in a recent build matching the April 5 2023 commit "fixed swapped language IDs for Norwegian and Dutch."; The problem is still reproduced in or near the slime pools found in E1L6 and E2L6. Here's a screenshot from E2L6 - slime palette is expected, but I get the water palette instead:

![Duke_0013](https://user-images.githubusercontent.com/6780140/230468111-794d822a-6e01-4cc2-b36e-e855726e5caf.png)
