### ISSUE TITLE
[BUG] Crash when starting $woods (Dark Woods of the Serpent)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#804]
### Raze version

master ab97f00cd1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If I try to go to $woods (Dark Woods of the Serpent) by starting a new game on that level, or finishing the previous level ($shrine, Master Leep's Temple), the game just crashes. Unfortunately, even ASan can't catch the crash. I provided a crash log below, if it is any help.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Enter `map $woods` into the console

### Provide a Log

[raze-crash.log](https://github.com/ZDoom/Raze/files/10254827/raze-crash.log)

**Comment by EdHerdman** [comment]
Duplicated on Windows 11, and this platform is able to generate a full Crash Report along with the minidump.
[CrashReport.zip](https://github.com/ZDoom/Raze/files/10255629/CrashReport.zip)

**Comment by Talon1024** [comment]
I just took a quick look into the issue using GDB, and on this line:

https://github.com/ZDoom/Raze/blob/ab97f00cd15b7740301dc8b4921237283d25f631/source/games/sw/src/sprite.cpp#L1527

pp->actor seems to be a null pointer...

**Comment by mjr4077au** [comment]
Thanks for checking on that. The issue is occurring because we eliminated the player's unique position and just use the player actor's sprite position and now we have a race condition. 

I'm not in front of my main rig for now but its likely that the call to `PreMapCombineFloors()` just needs to be moved underneath `InitAllPlayerSprites()`, though I can see something inside `PreMapCombineFloors()` that will also need changing. 

I'll look at this one tonight, probably in ~3 hrs or so.

**Comment by mjr4077au** [comment]
Sorry, this will be a weekend fix now. Between work, family and feeling a bit crook this week I just can't find the time at this stage.
