### ISSUE TITLE
Shadow Warrior "ninja slice animation" setting appears reversed

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/Raze#817]
Shadow Warrior, Win10-64, Raze 1.6.1.

I believe the "ninja slice animation" setting is reversed. When it shows "off" in the settings menu, enemies are carved in two by the Katana.

**Comment by mjr4077au** [comment]
It's the right way around as off is the default animation. It probably should be renamed "Alternative ninja animations" or something to that effect to eliminate confusion.

**Comment by ninjakitty844** [comment]
"Alternative ninja slice"
or
"Shorter ninja slice"

would work too imo

**Comment by ninjakitty844** [comment]
too lazy to fill out another bug report right now, but when this option is enabled, ninjas choking on their own blood will instead eat an uzi lollipop. i feel like leaving in their choking animation would make more sense since this option does not seem shorten the time it takes for ninjas to choke anyway.

the option is also not saved. if you turn it on in miscellaneous options, and then restart raze, it will no longer be enabled.

**Comment by mjr4077au** [comment]
The option not being saved can be easily fixed, but please stop hijacking other reports...

**Comment by mjr4077au** [comment]
Save issue fixed in 6065140f6805fdb840df8da41b062397a6b0853f. I can't tell whether `CVAR_SERVERINFO` was there for a reason, and if so and it comes back, it will make it not persist between sessions again.
