### ISSUE TITLE
[BUG] [Duke Caribbean: Life's a Beach] Weird ceiling in E3M3 (Mr. Splashy's)

### ISSUE THREAD

**Issue by valter12437** [ZDoom/Raze#842]
### Raze version

Raze 1.6.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

AMD Ryzen 3 3200g with Vega 8 graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The ceiling in Mr. Splashy's level in coords X: -436 Y: 1736 / X: 47 Y: 2083 uses skybox tiles and therefore look weird in the new renderer.

This is what the ceiling looks like in Raze's renderer:
![20230106204905_1](https://user-images.githubusercontent.com/82282361/211151688-d411c3f0-6820-41f6-a002-16860fe70352.jpg)

This is what the ceiling looks like in EDuke32 with the "Classic Renderer":
![duke0001](https://user-images.githubusercontent.com/82282361/211151753-686605f6-cfe7-4b5b-a20e-c3380bfc9e5e.png)

This is what the ceiling looks like in EDuke32 with the  "Polymost Renderer":
![duke0003](https://user-images.githubusercontent.com/82282361/211151818-b81e1d6c-1b98-41cf-a101-13cad5f6ddda.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to the specified coordinates.
2. Look at the ceiling.
3. That's it really.

**Comment by coelckers** [comment]
Yeah, they used a texture on the sky which the flat renderer could not handle. The differences between Polymost and our new renderer comes from some fixes we made to texture positioning that caused bad alignments in some RR maps.

Short of replacing the texture I am sorry, this is not fixable - it depends on the software renderer misinterpreting the texture's size due to shit coding.
