### ISSUE TITLE
[BUG] Kimono-clad statues(?) cannot be destroyed

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#873]
### Raze version

Raze 1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The kimono-clad statues(?) on E3L1 cannot be destroyed. IIRC, they are supposed to break into glass shards when shot at.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10576361/statues.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on E3L1
2. Shoot at one of the kimono-clad asian woman statues
3. They cannot be destroyed

**Comment by EdHerdman** [comment]
I bet the protector drone breakage is due to the same changes. There's a lot of new deprecated actor warnings in zscript on loading the game.

About half the enemies in Nuclear Winter are broken: Pig cops, all the snowmen varieties except the Assault Commander-based one, the sled tanks, the elves. They'll just rotate to face the player on being hit, but do nothing else. The enemies still apparently working include the Troopers, Enforcers, Slimers, Commanders.

**Comment by mjr4077au** [comment]
DIfferent issue. Bisected back to 4397e65443015db7b8891398d534d93ebd59cb31.

**Comment by coelckers** [comment]
fixed in ede52f2ddefa875f4681866f68a6ababc98f07ed
