### ISSUE TITLE
[BUG] [Duke DC] Pistol autoaim offset badly near the end of DUKEDCSL

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#874]
### Raze version

Raze 1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The pistol's aim is offset badly within the sloped sectors near the end of the Duke it out in DC secret level. If you try to aim at an enemy, the bullets will not hit the target. Instead, the bullets will be aimed way above the enemy's head.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10576553/bullet.aim.off.zip)

I haven't been able to reproduce this issue on a vanilla Duke Nukem 3D level yet, unfortunately.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Shoot at an enemy when you are standing in one of the sloped sectors. 
3. The bullets will be aimed far above the enemy
4. This does not happen with the Shotgun or Chaingun

**Comment by mjr4077au** [comment]
While the autoaim isn't working (and hasn't been since as far back as 0.7.3 from my testing), I'm more curious about the sprite going into the ground:

![image](https://user-images.githubusercontent.com/48643140/216813891-c5e761c0-bbbc-425e-9276-74cdc81fba39.png)

This also happens in EDuke32, however the autoaim does function correctly here.

![image](https://user-images.githubusercontent.com/48643140/216813882-71021df7-8f29-40ab-9e34-18b8771709e0.png)

While the autoaim should be fixed to handle this, the sprite should probably be factoring in the slope when calculating its Z and not just using the floor's Z.

**Comment by coelckers** [comment]
I have to wonder if the autoaim thing is an EDuke32 bugfix or an error on our side. Having seen several similar issues in Duke I wouldn't consider it imposslble for this to be a vanilla bug.

**Comment by mjr4077au** [comment]
Re-opening as I don't believe it was meant to be closed. Too easy to hit the close button when replying.

**Comment by Talon1024** [comment]
It works just fine in Duke Nukem 3D: Megaton Edition.

**Comment by coelckers** [comment]
I recently fixed another autoaim issue with the pistol, which mainly affects the mosquitos and chickens in RR, but since the end result was also to aim above the target it makes me wonder if this is the same thing.
