### ISSUE TITLE
[Question] Translating tiles HUD related files

### ISSUE THREAD

**Issue by Blueberryy** [ZDoom/Raze#881]
Is it possible to make translations support for tiles images? For example [2200.png](https://github.com/ZDoom/Raze/blob/master/wadsrc/static/filter/blood/tiles/2200.png) would be 2200_*insert language id here*.png and will change if player changed language to it if it's supported.
I really enjoy zdoom and raze so just asking if developers have any solutions on that!

**Comment by coelckers** [comment]
Such a feature theoretically exists in the engine, but I disabled it because it has a detrimental effect on texture lookup (i.e. normal lookup from texture ID to texture is very fast and can be inlined, but with the localization lookup it has to check a remapping table each time), and additionally requires special handling to avoid being stuck with the base texture. In general I don't think this is really worth bothering. The only screens that may require handling are Duke's end of game text screens but I'd approach those a bit differently (i.e. separating the text from the base layer instead of providing separate graphics.)

**Comment by Blueberryy** [comment]
Make sense. Thank you for the info
