### ISSUE TITLE
[BUG] Player does not sprint using XInput controller left stick

### ISSUE THREAD

**Issue by alpozcan** [ZDoom/Raze#903]
### Raze version

1.6.2

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 11

### Relevant hardware info

Xbox series controller

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Player does not sprint using XInput controller even with 'always run' set to true. Keyboard WASD keys work fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Turn on controller
2. Launch game
3. Start new game
4. Push left stick all the way -> Duke still moves at walking speed
5. Use WASD keys -> Duke moves at running speed

### Your configuration

```ini
cl_runmode=true
```

in every occurence of that cvar in the .ini.
```


### Provide a Log

_No response_

**Comment by mjr4077au** [comment]
This is already addressed in eed9716d86d66f6aedbeca6f989784b7cd1068db, but for now all you need to do is set the stick's sensitivity to 2.

Back in the early days when I was getting the controller code going, I halved the forward/side speed to give the player more tunability down low. I didn't understand why the slider went to 4 when 1 was full speed. I regret doing this because it's been a constant source of confusion for everyone and now it's gone.

**Comment by alpozcan** [comment]
thanks Mitchell!

**Comment by mjr4077au** [comment]
From a fellow Coastie in Narara, you're most welcome :)
