### ISSUE TITLE
[BUG] Quicksave rotation doesn't work

### ISSUE THREAD

**Issue by axredneck** [ZDoom/Raze#909]
### Raze version

Commit 9618ba1e7875ad4adeb40bfc24d5e17577dac507

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Unlike GZDoom, Raze always quicksaves to the same file, even if "Number of quicksaves in Rotation" is bigger than 1.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set quicksavecount to 2 or more
2. Start playing
3. Quicksave
4. Quicksave again

### Your configuration

```ini
https://gist.github.com/axredneck/5e05428758face0dc10bc85f8ceb3517
```

**Comment by coelckers** [comment]
I plan to address this once I know what people's preferences are. Optimally we can just remove the stupid original quicksaving entirely and make rotating quicksaves the only option and the default.

**Comment by Talon1024** [comment]
Removing the "stupid" original quicksaving will force people to have only one ongoing playthrough at a time, or press F2 for a manual save (a minor inconvenience). I'm the kind of player who likes to have multiple ongoing playthroughs, and I often come back to other ongoing playthroughs whenever I get tired during the current playthrough.

**Comment by ja3h** [comment]
Since the original bug has been acknowledged, can I piggyback on this to note another quicksave annoyance to consider if replacing the quicksave system? 
I tested it in both Blood and Duke. 
If I quicksave then close the game, load the save back and then press F6 to quicksave back over the quicksave, pressing Enter will assume I'm using the virtual keyboard beneath it and enter an 'A' rather than just automatically using the name I used before. This feels like unnatural behaviour as the originals didn't do this and neither does Nblood. Cheers!
