### ISSUE TITLE
[Tech Issue] [Duke 3D] Total freeze of PC

### ISSUE THREAD

**Issue by vadim-zyamalov** [ZDoom/Raze#94]
Bumped into an issue with the late Raze version.
Used to it to play Duke3D Atomic Edition. Game usually works smoothly without any problems, but twice I got PC **totally** frozen (absolutely not responding to **any** keypresses with buzz from PC speakers).

I've attached an archive with log and settings.
[Raze.zip](https://github.com/coelckers/Raze/files/5299024/Raze.zip)

My PC specs: Windows 10 Home v.2004, Core i3-3220, integrated Intel video, 8G RAM

**Comment by coelckers** [comment]
A total freeze of the system is normally a very bad sign that you may be developing a hardware problem - a regular application cannot lock up a system like this - that requires a malfunction on the driver level. 
For now there's not really much I can recommend, aside from trying to run with Vsync enabled to reduce the load on your GPU and CPU.

**Comment by sinisterseed** [comment]
Seconding Graf here, this is a very clear indication of something going very bad either at hardware or driver level. Playing a game and having the PC locking up, BSODing, restarting, and so on is a sign of something going nuts elsewhere, rather than in the program itself.

**Comment by sinisterseed** [comment]
Looking over your specs, I noticed you're running on integrated graphics, on a pretty old CPU generation no less.

First thing I want to say here is to update your drivers if they aren't already, Intel graphics are notoriously temperamental when it comes to games, so that's what I could check first.

**Comment by d9d6ka** [comment]
Kernel-Power, EvendID: 41, Keywords: 0x8000400000000002.

Yeah, my PC is 6yo. I've Intel Driver & Support Assistant installed so all drivers are updated. Seems that my PC is just slowly dying and the problem is highly likely due to HW.

Sorry for panic and disturbing you. And great thanks for the alternative Duke engine port 'cause two is better than one!

**Comment by sinisterseed** [comment]
Perhaps, but the CPU itself is surely older than that, Ivy Bridge CPUs originally came out in 2012, so that means you're running hardware that's historically 8 years old at this point, it has since been classified as "legacy" on Intel's page and driver support is likely... not great for nowadays - https://ark.intel.com/content/www/us/en/ark/products/65693/intel-core-i3-3220-processor-3m-cache-3-30-ghz.html

I've browsed through its specs at it should technically be capable of running Raze just fine, but unfortunately the age of the hardware seems to start showing up. Thank you for the kind words though, we appreciate it :) , it's just too bad you can't experience our port adequately at this time.
