### ISSUE TITLE
[BUG] [SW] Several issues

### ISSUE THREAD

**Issue by Switch123456789** [ZDoom/Raze#979]
### Raze version

1.8pre-539

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch (latest)

### Relevant hardware info

Ryzen 2600x | GTX 1060 (6GB)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I recently played through the entirety of Shadow Warrior and I found a bunch of issues and decided to take notes. I hope you can forgive me for reporting them in a single bug report.

I am planning on updating this post and/or remove bugs with existing reports and/or branch them out in a dedicated report if needed/wanted.

**Graphical issues:**

- Lo Wang's sprite is animated as if he is running while standing and vice versa.
- Disabling fog disables all lightning/shadows in the whole game.
- The original game applies a blue tint to the whole screen which imo should be applied to raze as well, just with the HUD excluded.
![water](https://github.com/ZDoom/Raze/assets/25269380/c5809634-beb9-4f2a-b31a-df8b95d1943b)
- (VOLCANO.MAP) I am not sure about this one but is this grid supposed to look transparent? 
![15](https://github.com/ZDoom/Raze/assets/25269380/104d1e56-374c-4bf2-99fc-b5103b9c6f77)
- (SHRINE.MAP) The colors of some sprites look broken, I found more of these throughout the game. I think it mainly applies to hanging objects.
![2a](https://github.com/ZDoom/Raze/assets/25269380/28bc6ca1-f02e-42f8-b4b5-4d75f8a33821)
![2b](https://github.com/ZDoom/Raze/assets/25269380/e877c498-3053-43bf-a5d1-065c8d08088a)
![2c](https://github.com/ZDoom/Raze/assets/25269380/2c4eb16a-9f1a-4119-bd9d-09dc60e1f698)
![2d](https://github.com/ZDoom/Raze/assets/25269380/1283de9d-d035-4069-be38-2b8d74a017df)

**Gameplay:**
- If I finish a level and load a savegame from the same level after the next level has been loaded, the trigger breaks that would load the next Level (dead endboss or pressing the yingyang-button | It seems to be the same with Duke Nukem 3D)
- ~~NPC's mostly wont cross edges or walk into other rooms (not sure if this is supposed to be like that?!)~~
- in some cases there is an offset between the center of the crosshair and the spot Lo Wang is actually shooting at. Especially noticeable on some vehicles.
- Some enemy turrets aim in one direction but their projectiles shoot in another direction.
- (YAMATO.MAP) If I jump onto the edge at which the crosshair is pointing at in the screenshot. The game throws me to another part of the map.
![11](https://github.com/ZDoom/Raze/assets/25269380/53724c26-9988-4ea3-9f2d-2768e210d207)
- (SEABASE.MAP) If I jump down this edge, I won't land on the ground, I will drop trough it into the water every time.
![12](https://github.com/ZDoom/Raze/assets/25269380/368e856f-ab8a-4e12-91e6-fac99eb8dabd)

### [Configuration](https://github.com/ZDoom/Raze/files/12138517/cfg.txt)

**Comment by ninjakitty844** [comment]
**Some corrections:**
(DOS SW is the original game, so it is the "not bugged" version, if you will)

"On some occasions some enemy-sprites flip upside-down whenever they (are about to) die."
_Some enemies DO actually flip upside down when they die, this is a feature. Ninjas and coolie ghosts do this for example, even in DOS SW._

"If Lo Wang is on fire, there is a flame following him with a small delay."
_This is also present in DOS SW._

"The original game applies a blue tint to the whole screen which imo should be applied to raze as well, just with the HUD excluded."
_I would like to bring up another issue here, the blue tint is CLEARLY much weaker in Raze. In Raze you can't even tell that the tint is being applied to Wang's hands, it's just so weak. And the fog is so much weaker. Would love for this to be fixed._

"(VOLCANO.MAP) I am not sure about this one but is this grid supposed to look transparent?"
_I'm about 90% sure its not supposed to look transparent, as it doesn't look transparent in any other Shadow Warrior port that I know of._

"(SHRINE.MAP) The colors of some sprites look broken, I found more of these throughout the game. I think it mainly applies to hanging objects."
_Interestingly, I had a similar issue with that exact sprite. Thought it was just me._

"Sometimes when I press the action-key to interact with an object, Lo Wang grunts as if there is nothing I can interact with while he actually interacts with it successfully . I can't notice a pattern for when this happens."
_This is present in DOS SW._

"NPC's mostly wont cross edges or walk into other rooms (not sure if this is supposed to be like that?!)"
_Depends on the map, MANY maps have invisible walls that actors can't pass through, and it is an intentional map design decision. For example the rippers in the hallway, level 1 of Code of Honor, they can't exit the hallway into the area with the statue._

"(VOLCANO.MAP) The Endboss's circling explosive skulls sometimes glitch through walls while being attached to the boss."
_This is present in DOS SW, not a bug._

"(SEABASE.MAP) If I shoot at the window with this remote controlled gun, I take damage through the window."
_This is not a bug, but a map design oversight. That isn't a window you're looking through, there's technically no physical wall there, it's just set so you can't walk through. Therefore explosions can go through it. It's the same in DOS SW_

**Comment by Switch123456789** [comment]
> Some enemies DO actually flip upside down when they die

I see, however, I had it happen to almost all enemies randomly and it doesn't happen always.

Are you sure about the following flame? It is REALLY janky & disorienting when that happens, it is hard to believe they would ship the game like this.

> I feel like this is because Raze uses a tint and doesn't use the actual underwater palette EVEN if you have palette emulation enabled

I heard that "[non-black fog does not use palette emulation](https://github.com/ZDoom/Raze/issues/981#issuecomment-1646902756)".

**Comment by ninjakitty844** [comment]
> > Some enemies DO actually flip upside down when they die
> 
> I see, however, I had it happen to almost all enemies randomly and it doesn't happen always.
> 
> Are you sure about the following flame? It is REALLY janky & disorienting when that happens, it is hard to believe they would ship the game like this.
> 
(https://github.com/ZDoom/Raze/issues/981#issuecomment-1646902756)".

I highly suggest that you play the original game in Dosbox, and only report things that are clearly broken and different from that version. The slight flame delay, the enemies flipping upside down, etc are all just quirks of the game working as intended. Also one bug report at a time would be easier for the devs to digest.

**Comment by Switch123456789** [comment]
I do test things in DOSBox occasionally. However, I probably misunderstood the mission-statement of raze since I was under the impression bugfixes & other improvements are part of it. I found it hard to test things in the original-game because the lack of a dev-console, any suggestions would be appreciated. My apologies for doing it this way, I felt uncomfortable to do a flood of bug  reports. I will do so from now on.
